# Generated by Django 4.2.12 on 2024-05-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_options_alter_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'can view history')]},
        ),
    ]
